<nav id="quicklinks" role="navigation" aria-label="quick links" aria-hidden="true">
    <ul id="big-links"> 
        <li><span class="icon-myuw"></span><a href="http://myuw.washington.edu" tabindex="-1">MyUW</a></li> 
        <li><span class="icon-calendar"></span><a href="http://uw.edu/calendar" tabindex="-1">Calendar</a></li> 
        <li><span class="icon-directories"></span><a href="http://uw.edu/directory/" tabindex="-1">Directories</a></li> 
        <li><span class="icon-libraries"></span><a href="http://www.lib.washington.edu/" tabindex="-1">Libraries</a></li> 
        <li><span class="icon-medicine"></span><a href="http://www.uwmedicine.org/" tabindex="-1">UW Medicine</a></li> 
        <li><span class="icon-maps"></span><a href="http://uw.edu/maps" tabindex="-1">Maps</a></li> 
        <li><span class="icon-uwtoday"></span><a href="http://www.uw.edu/news" tabindex="-1">UW Today</a></li>
    </ul>
    <h3>Helpful Links</h3>
    <ul id="little-links">
        <li><span class="false"></span><a href="http://www.washington.edu/itconnect/forstudents.html" tabindex="-1">Computing/IT</a></li> 
        <li><span class="false"></span><a href="http://f2.washington.edu/fm/payroll/payroll/ESS" tabindex="-1">Employee Self Service</a></li> 
        <li><span class="false"></span><a href="http://www.hfs.washington.edu/huskycard/" tabindex="-1">Husky Card</a></li> 
        <li><span class="false"></span><a href="http://www.bothell.washington.edu/" tabindex="-1">UW Bothell</a></li> 
        <li><span class="false"></span><a href="http://www.tacoma.uw.edu/" tabindex="-1">UW Tacoma</a></li> 
        <li><span class="false"></span><a href="https://www.facebook.com/UofWA" tabindex="-1">UW Facebook</a></li> 
        <li><span class="false"></span><a href="https://twitter.com/UW" tabindex="-1">UW Twitter</a></li>
    </ul>
</nav> 